<?php
/**
 * Created by PhpStorm.
 * User: lifarav
 * Date: 11.09.2016
 * Time: 20:25
 */

namespace Twet\Frontend\Controllers;

use Twet\Frontend\Models\User;

class AuthController extends ControllerBase
{

    public function beforeExecuteRoute()
    {
        //parent::beforeExecuteRoute(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        if ($this->request->isPost()) {

            $email = $this->request->getPost('email', 'email');
            $password = $this->request->getPost('password');

            $user = User::findFirstByEmail($email);

            if (!$user) {
                //$this->response->redirect($this->config->hosts['main']);
            }

            if (!$this->getDI()->get('security')->checkHash(trim($password), $user->password)) {
                //$this->response->redirect($this->config->hosts['main']);
            }

//            $this->response->redirect($this->config->hosts['main'] . '/' . $this->auth->homeLoggedUrl);


        }
        //$this->auth->getSessionFromCookie();
    }

    public function redirectAction()
    {

    }
}