<?php echo $this->tag->getDoctype(); ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <title>Twet</title>
        <link rel="icon" href="<?=$this->url->getStatic('img/favicon.png');?>" type="image/png">
        <?php
            echo $this->tag->javascriptInclude('js/jquery-3.1.0.min.js');
        ?>
    </head>
    <body>
<?php echo $this->getContent() ?>

    </body>
</html>