    <?php
    echo $this->tag->form([
        'signin',
        'method' => 'post',
        'id' => 'signin'
    ]);
    ?>

    <?php echo $form->render('email'); ?>
    <?php echo $form->render('password'); ?>


    <input type="submit" value="Отправить">

    <button id="btn-signin-twitch"><h4>Connect with Twitch</h4></button>

    <script>
        $('#btn-signin-twitch').bind('click', function(){
            window.location.href = "https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=ru0xspiy28g46max3mqdxuywpc4za16&redirect_uri=<?=$this->config->hosts['main'];?>/twitch/callback&scope=channel_read";
        })
    </script>


    <?php
    var_dump($this->auth->isGuest());
    var_dump($this->auth->isInitialized());
    var_dump($this->getDI()->getShared('cookies')->get('Session')->getValue());
    ?>

    <script>
        $(function() {
            $('#signin').submit(function(e) {
                var $form = $(this);
                $.ajax({
                    type: $form.attr('method'),
                    url: $form.attr('action'),
                    data: $form.serialize(),
                    success: function(data){
                        console.log(data);
                    }
                });
                //отмена действия по умолчанию для кнопки submit
                e.preventDefault();
            });
        });
    </script>
